import React, {Props} from "react";
import {navigate} from "@reach/router";
import { Formik, Field, Form } from "formik";

function DeletePost() {
  
  const handleSubmit = values => {
    const requestPosts = async () => {
      // We get the CSRF token generated by Rails to send it
      // as a header in the request to create a new post.
      // This is needed because with this token, Rails is going to
      // recognize the request as a valid request
      const csrfToken = document.querySelector("meta[name=csrf-token]").content;
      const response  = await fetch("/api/posts/" + id, {
        method: "DELETE",
        credentials: "include",
        headers: {
          "Content-Type": "application/vnd.api+json",
          "X-CSRF-Token": csrfToken
        },
       
      });

      if (response.status===204) {
        navigate("/");
      }
    };
    requestPosts();
  };
  const id = window.location.pathname.slice(5);
  return (
    <div>

  <p>{id}</p>
  <p>Delete Post</p>

    <button onClick={()=>handleSubmit()}>Delete</button>
    <button onClick={()=> navigate('/')}>
    Back
    </button>
    </div>
  );
}

export default DeletePost;