import React, {Props} from "react";
import {navigate} from "@reach/router";
import { Formik, Field, Form } from "formik";

function EditPost() {
  const handleSubmit = values => {
    const requestPosts = async () => {
      // We get the CSRF token generated by Rails to send it
      // as a header in the request to create a new post.
      // This is needed because with this token, Rails is going to
      // recognize the request as a valid request
      const csrfToken = document.querySelector("meta[name=csrf-token]").content;
      const response = await fetch("/api/posts/" + id, {
        method: "PATCH",
        credentials: "include",
        headers: {
          "Content-Type": "application/vnd.api+json",
          "X-CSRF-Token": csrfToken
        },
        body: JSON.stringify({ data: {id:id,type:"posts", attributes:{title:values.attributes.title,body:values.attributes.body}} })
      });
      if (response.status === 201) {
        navigate("/");
      }
    };
    requestPosts();
  };
  const id = window.location.pathname.slice(6);
  return (
    <div>

  <p>{id}</p>
  <p>Edit Post</p>
      <Formik
        initialValues={{
          type: "posts",
          attributes: {
            title: "",
            body: ""
          }
        }}
        onSubmit={handleSubmit}
        render={() => (
          <Form>
            <Field type="text" name="attributes.title" />
            <Field type="text" name="attributes.body" />

            <button type="submit">Create</button>
          </Form>
        )}
      />
    <button onClick={()=> navigate('/')}>
    Back
    </button>
    </div>
  );
}

export default EditPost;