import React, {Props, useState, useEffect} from "react";
import {navigate} from "@reach/router";
import { Formik, Field, Form } from "formik";


function EditPost(props) {  
   
  //Function to handle the editing of values in database after submission
  const handleEdit = values => {
    const requestPosts = async () => {
      // We get the CSRF token generated by Rails to send it
      // as a header in the request to create a new post.
      // This is needed because with this token, Rails is going to
      // recognize the request as a valid request
      const csrfToken = document.querySelector("meta[name=csrf-token]").content;
      const response  = await fetch("/api/posts/" + id, {
        method: "PATCH",
        credentials: "include",
        headers: {
          "Content-Type": "application/vnd.api+json",
          "X-CSRF-Token": csrfToken
        },
        body: JSON.stringify({ data: {id:id,type:"posts", attributes:{title:values.attributes.title}} })
      });
      if (response.status===200) {
        window.history.back();
      }
    };
    requestPosts();
  };
  
  //Getting id number of data
  const id = props.id;

  //Fuction to ensure posts are not empty
  function validate(value){
    let error;
    if(!value){
      error = "Required";
    }
    return error;
  }

  //Function to return the display in html
  function displayEdit(){

    return (
      <div>
        <h3 class="m-4">Edit Post</h3>
        <Formik
          initialValues={{
            type: "posts",
            attributes: {
              title: ""
            }
          }}
          onSubmit={handleEdit}
          render={() => (
            <Form>
              <Field class="ml-2" type="text" validate={validate} name="attributes.title" placeholder="New Title" />
              <button class="btn btn-warning ml-2" type="submit">
                Edit
              </button>
            </Form>
          )}
        />
        <button class="btn btn-info m-2" onClick={()=> window.history.back()}>
          Back
        </button>
      </div>
    )
  }
  

  return (
    displayEdit()
  )
}

export default EditPost;